### ISSUE TITLE
Partner add on and deploy options in a single location

### ISSUE THREAD

**Issue by rorzari** [aws-samples/eks-anywhere-addons#102]
Make it easier for users to find the comprehensive list of partners with solutions that have been validated for EKS-A using Conformitron. Currently, an user needs to navigate under [validated partners folders](https://github.com/aws-samples/eks-anywhere-addons/tree/main/Validated_Partners)--each representing an EKS-A deploy option--and open .txt files to find a given partner has an EKS-A add on published. An unified 'view' showing partner company name, product/solution (SKU), product version, K8s/eks-a version, date the add on was created/published, and list of compatible eks-a deploy options make it easier for an user to easily/quickly identify partners, products, validated to a given eks-a deploy options.

For example, each row would display something along the lines:

<partner company>, <product name>, <product version>, <eks-a/kubernetes version>,bare metal, outpost, snow, vsphere.

**Comment by elamaran11** [comment]
@rorzari Great suggestion, we will implementing this when we work complete the work with extrapolating these validated partner folders to AWS Docs pages

**Comment by elamaran11** [comment]
@rorzari We have implemented a Doc in EKS-A Public pages to reflect this behavior. Closing this issue.
