### ISSUE TITLE
Sample Tester manifest is Job, should be CronJob

### ISSUE THREAD

**Issue by jkodroff** [aws-samples/eks-anywhere-addons#142]
The Sample test job https://github.com/aws-samples/eks-anywhere-addons/blob/main/eks-anywhere-common/Testers/Sample/testJob.yaml is a `Job` and should be a `CronJob`.

**Comment by jkodroff** [comment]
It looks like it's wrong in multiple files (`eks-anywhere-*/Testers/Sample/testJob.yaml`)

**Comment by elamaran11** [comment]
Thanyou @jkodroff for this issue, we will work on this.

**Comment by elamaran11** [comment]
@mikemcd3912 Please add this to your backlog. Our sample job needs to be updated for `CronJob`

**Comment by jkodroff** [comment]
@elamaran11 Is there a trick I might not know about to keep the resource as a `CronJob` but still making it easy to test like a `Job` is? e.g. Is there a way to keep the common "work" separate from the scheduling part?

**Comment by elamaran11** [comment]
@jkodroff Not sure i understand your question because once you change to CronJob it runs a Job on schedule which is what we want to do with this.
