### ISSUE TITLE
Work with partners Sysdig to submit Test Job with Functional Test Requirements

### ISSUE THREAD

**Issue by elamaran11** [aws-samples/eks-anywhere-addons#226]
**Is your feature request related to a problem? Please describe.**
Work with partners Sysdig to submit Test Job with [Functional Test Requirements](https://aws-samples.github.io/eks-anywhere-addons/#functional-job-requirements).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by elamaran11** [comment]
@manuelbcd Appreciate if you can work on this ticket pls. We need continuous maintenance of versions and also the test job is incompliant.

**Comment by elamaran11** [comment]
@manuelbcd Any updates on this. We are on a risk of removing the software from the framework if there is no updates.

**Comment by elamaran11** [comment]
@manuelbcd We still dont see any PR for this request. We need continuous maintenance and also test job is out of compliance.  We are on a risk of removing the software from the framework if there is no updates.

**Comment by elamaran11** [comment]
@manuelbcd  Please provide an update on this. We have to remove dynatrace if there is no updates by end of month. We want all ISV products to be compliant.

**Comment by mikemcd3912** [comment]
Hi @manuelbcd, Just in case you hadn't seen the AWS Developers slack communication I wanted to leave a comment here as well - Do you have any updates on the timeline for the functional testing? As Ela mentioned previously we will need to remove the Sysdig Addon at the end of the month until that functional testing is brought into compliance with our new requirements unless we see some movement on the update
